behaviors:
  Turtle:
    trainer_type: sac
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      buffer_init_steps: 5000
      learning_rate: 3e-4
      tau: 0.005
      steps_per_update: 8
      init_entcoef: 0.2
      reward_signal_steps_per_update: 1
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1_000_000
    time_horizon: 64
    summary_freq: 50_000
    checkpoint_interval: 500_000
    keep_checkpoints: 5
